title: Schulsani Link Shortener
description: âœ‚ï¸ğŸ”— This is a template repository for making URL Shorteners with Jekyll and GitHub Pages. Create short URLs that can be easily shared, tweeted, or emailed to friends.
logo: /assets/jf-logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

github: [metadata]
