title: Schulsani Link Shortener
description: âœ‚ï¸ğŸ”— Auf Dieser Webseite findes du Links in Bezug auf das Schulsani Alarmierungs Jugendforscht Projekt.
logo: /assets/jf_logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

github: [metadata]
